### ISSUE TITLE
UnBoundLocalError

### ISSUE THREAD

**Issue by iPsych** [clovaai/stargan-v2#28]
Similar to issue #11 

After train, eval error happens when use 4 domains dataset.

Should I adjust lambda_ds for #domains-1, or adjust other variable to fit with # of domains?

```
python main.py --mode train --num_domains 4 --w_hpf 0 \
               --lambda_reg 1 --lambda_sty 1 --lambda_ds 1 --lambda_cyc 1 \
               --train_img_dir data/custom/train \
               --val_img_dir data/custom/val
```

```
Calculating evaluation metrics...
Number of domains: 4
Preparing DataLoader for the evaluation phase...
Traceback (most recent call last):
  File "main.py", line 182, in <module>
    main(args)
  File "main.py", line 59, in main
    solver.train(loaders)
  File "/home/ipsych/ML/Stargan_v2/core/solver.py", line 170, in train
    calculate_metrics(nets_ema, args, i+1, mode='latent')
  File "/home/ipsych/.conda/envs/Pytorch_1_4_0/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ipsych/ML/Stargan_v2/metrics/eval.py", line 61, in calculate_metrics
    iter_ref = iter(loader_ref)
UnboundLocalError: local variable 'loader_ref' referenced before assignment

```

**Comment by yunjey** [comment]
@iPsych Please use the updated [code](https://github.com/clovaai/stargan-v2/blob/master/metrics/eval.py#L75-L79). [This commit](https://github.com/clovaai/stargan-v2/commit/896c88409050f5d0f7b4f7c7de742213733eb419) should resolve the error.

**Comment by Johnson-yue** [comment]
@yunjey I try [This commit](https://github.com/clovaai/stargan-v2/commit/896c88409050f5d0f7b4f7c7de742213733eb419) and it fixed "StopIterationError" but not fix "UnboundLocalError" , as my test

**Comment by iPsych** [comment]
@yunjey @Johnson-yue I am experiencing same issue related to loader_ref.

**Comment by Johnson-yue** [comment]
@iPsych  I know that ，and I have same issue， maybe it was caused by different num_domains

**Comment by iPsych** [comment]
@yunjey Hi,
Does number of domains, or number of images for eval (currently very smaller than train images) can cause the problem?

**Comment by iPsych** [comment]
@yunjey 
Below is full log
```
Preparing DataLoader for the evaluation phase...
Preparing DataLoader for the evaluation phase...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:02<00:00,  8.97it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  4.06it/s]
Calculating evaluation metrics...
Number of domains: 4
Preparing DataLoader for the evaluation phase...
Preparing DataLoader for the evaluation phase...
Generating images and calculating LPIPS for Happy2Fear...
  0%|                                                                                                                                           | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ipsych/ML/stargan-v2/metrics/eval.py", line 76, in calculate_metrics
    x_ref = next(iter_ref).to(device)
UnboundLocalError: local variable 'iter_ref' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 182, in <module>
    main(args)
  File "main.py", line 59, in main
    solver.train(loaders)
  File "/home/ipsych/ML/stargan-v2/core/solver.py", line 171, in train
    calculate_metrics(nets_ema, args, i+1, mode='reference')
  File "/home/ipsych/.conda/envs/Pytorch_1_4_0/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ipsych/ML/stargan-v2/metrics/eval.py", line 79, in calculate_metrics
    x_ref = next(iter_ref).to(device)
  File "/home/ipsych/.conda/envs/Pytorch_1_4_0/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/ipsych/.conda/envs/Pytorch_1_4_0/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 831, in _next_data
    raise StopIteration
StopIteration
```
I trained with custom dataset named EMO-S consists of four domains with below codes.

`python main.py --mode train --num_domains 4 --w_hpf 0 --lambda_reg 1 --lambda_sty 1 --lambda_ds 3 --lambda_cyc 1 --train_img_dir ./data/EMO-S/train --val_img_dir ./data/EMO-S/val`

**Comment by Johnson-yue** [comment]
@iPsych  This is **StopIteration** Error not _UnBoundLocalError_ and  **StopIteration** Error was fixed in [This commit](https://github.com/clovaai/stargan-v2/commit/896c88409050f5d0f7b4f7c7de742213733eb419) I have checked . So maybe you upload false  log ???

**Comment by iPsych** [comment]
@Johnson-yue My bad.. The UnBoundLocalError disappeared, but StopIteration happens even with latest commit and latest sources. I

**Comment by iPsych** [comment]
@Johnson-yue, @yunjey 
I again face with the UnBoundLocalError with latest code. I patched eval.py with 
https://github.com/clovaai/stargan-v2/pull/9
but still face below errors.
```
3781] G/ref_sty: [0.1911] G/ref_ds: [0.6815] G/ref_cyc: [0.2138] G/lambda_ds: [1.8000]
Saving checkpoint into expr/checkpoints/050000_nets.ckpt...
Saving checkpoint into expr/checkpoints/050000_nets_ema.ckpt...
Saving checkpoint into expr/checkpoints/050000_optims.ckpt...
Calculating evaluation metrics...
Number of domains: 3
Preparing DataLoader for the evaluation phase...
Traceback (most recent call last):
  File "main.py", line 182, in <module>
    main(args)
  File "main.py", line 59, in main
    solver.train(loaders)
  File "/home/ipsych/ML/stargan-v2/core/solver.py", line 170, in train
    calculate_metrics(nets_ema, args, i+1, mode='latent')
  File "/home/ipsych/.conda/envs/Pytorch_1_4_0/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ipsych/ML/stargan-v2/metrics/eval.py", line 61, in calculate_metrics
    iter_ref = iter(loader_ref)
UnboundLocalError: local variable 'loader_ref' referenced before assignment

```

**Comment by doantientai** [comment]
> @Johnson-yue, @yunjey
> I again face with the UnBoundLocalError with latest code. I patched eval.py with
> #9
> but still face below errors.
> 
> ```
> 3781] G/ref_sty: [0.1911] G/ref_ds: [0.6815] G/ref_cyc: [0.2138] G/lambda_ds: [1.8000]
> Saving checkpoint into expr/checkpoints/050000_nets.ckpt...
> Saving checkpoint into expr/checkpoints/050000_nets_ema.ckpt...
> Saving checkpoint into expr/checkpoints/050000_optims.ckpt...
> Calculating evaluation metrics...
> Number of domains: 3
> Preparing DataLoader for the evaluation phase...
> Traceback (most recent call last):
>   File "main.py", line 182, in <module>
>     main(args)
>   File "main.py", line 59, in main
>     solver.train(loaders)
>   File "/home/ipsych/ML/stargan-v2/core/solver.py", line 170, in train
>     calculate_metrics(nets_ema, args, i+1, mode='latent')
>   File "/home/ipsych/.conda/envs/Pytorch_1_4_0/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
>     return func(*args, **kwargs)
>   File "/home/ipsych/ML/stargan-v2/metrics/eval.py", line 61, in calculate_metrics
>     iter_ref = iter(loader_ref)
> UnboundLocalError: local variable 'loader_ref' referenced before assignment
> ```

That solution isn't correct. You should put the line `iter_ref = iter(loader_ref)` inside the condition `if mode == 'reference'` (a few lines above). Otherwise, it will crash the program because `loader_ref` is used before assignment.

**Comment by 1170300814** [comment]
i also have this error and use the lattest version of eval.py. how to solve it ?

**Comment by 1170300814** [comment]
@yunjey  that commit doesn't solve it

**Comment by aliwaqas333** [comment]
setting --val_batch_size=1 solves the issue.
